### ISSUE TITLE
Dependency.values() always accepts null

### ISSUE THREAD

**Issue by eboth** [dstreet/dependsOn#16]
Regardless of the content of the `values` qualifier (e.g. `['one', 'two', 'three']`), `Dependency.values()` always seems to accept `null` as a pass value.
As far as I could determine, this happens because of a chain of two unintuitive (to me) behaviours in JS and jQuery, respectively:
* `typeof(null) === object` is `true` (~ line 97 in dependsOn-1.0.1.js)
* `$('string').not($(null)).length === 0` is `true` (~ line 101 in dependsOn-1.0.1.js)

A workaround is to always specify the `not` qualifier when you want to exclude `null`, e.g.:
`$(selector).dependsOn({'#id': {values:['one', 'two'], not: [null]}});`

Overall, dependsOn is definitely the best invention since HTML forms and jQuery. Great documentation, very capable and it just works. Thanks David!

Endre

**Comment by dstreet** [comment]
@eboth, thanks for the kind words. Accepting `null` is certainly an issue. I'm working on v1.1.0, or I was until I got sidetracked, so I'll make sure to fix that in the next release. Thanks for the workaround!

**Comment by dstreet** [comment]
@eboth, I'm unable to recreate your issue. Can you post a snippet of the HTML and JS you are using, as well as the browser you're seeing the issue in?

**Comment by eboth** [comment]
I have reproduced it in Firefox 36 and IE 11 and also in this fiddle:
https://jsfiddle.net/frcg7fop/11/

In the fiddle JS, there are two condition definitions that should be equivalent: 
The one that works is `not: null`. 
The other that doesn't work is `values: ['KME', 'KOE']`, which should accept any of the two options in the master `<select>`, but should fail on page load when no option is selected. As you can see, it doesn't disable the slave `<select>` on page load.

**Comment by dstreet** [comment]
Thanks. This is now fixed in the v1.1.0 branch.

**Comment by eboth** [comment]
Many thanks for the speedy fix, David.

**Comment by ijasnijas** [comment]
Please merge this with master. I ahd to spend 2 days to find out the problem !!! Finally used v1.1.0

**Comment by dstreet** [comment]
There is more to do on v1.1.0 before it can be merged over, and sadly I haven't had much time to work on it.
