### ISSUE TITLE
Option to toggle the container of the input rather than ID & associated label

### ISSUE THREAD

**Issue by jameswragg** [dstreet/dependsOn#21]
Consider this markup:

    <div class="field">
        <label for="keywords">Keywords</label>
        <input id="keywords" name="keywords" type="text">
        <p>Pro tip: blah blah blah</p>
    </div>

Currently the protip would be left in limbo if hidden, it would be great to tell dependsOn to target the parent container of the target on show/hide operations.

**Comment by dstreet** [comment]
You could use the 'onEnable' and 'onDisable' callbacks to toggle the visibility of subject's parent container.

**Comment by jameswragg** [comment]
I'll take that! Cheers.
