### ISSUE TITLE
Cant make checked:true works, and value of that checked

### ISSUE THREAD

**Issue by ossvn** [dstreet/dependsOn#25]
Hello,

Thank you for your wonderful plugin, im using it for a project.

The idea is, user will select dependant fields. Exp:

Field A will appear when Field B "is checked" and "checked value is 123".

I dont know why but i can make it work with is, not, containt, but cant make it work with checked.

I hope you can give me an suggestion or how can i archive this?.

Thanks!

**Comment by dstreet** [comment]
I'm not sure what your code is like, but this works:

```
<input type="checkbox" id="dep" value="123">
<input type="text" id="subject">

<script>
	$(function() {
		$('#subject').dependsOn({
			'#dep': {
				checked: true,
				values: ['123']
			}
		})
	})
</script>
```

**Comment by ossvn** [comment]
let's me check around, since im intergrating your plugin to a project we're doing, it is combined with php and others stuff

Thank for your support mate!!

**Comment by ossvn** [comment]
@dstreet ah man, can you please do me ad favor? i really want to know how "match" work?, i tried to use 
match: [value], but the console gave me "f.test..." error, i tried to read again and again on documantation but there's no sample for match - regex?

**Comment by dstreet** [comment]
The `match` qualifier will return true when the RegExp matches. The below example will qualify if the value of `#dep` is exactly "123".

```html
$('#subject').dependsOn({
    '#dep': {
       matches: /^123$/
     }
 })
```

**Comment by ossvn** [comment]
it seem that i can combine several condition in the argument right mate?, as you wrote above, you can combile true and value to 123, what's the limit of the combination?, how much condition i can combine in 1 argument?

**Comment by dstreet** [comment]
You can use any or all of the qualifiers available.

**Comment by ossvn** [comment]
thanks buddy!, really helped me out!
