### ISSUE TITLE
Provide 'readonly' as an option in addition to 'disabled'

### ISSUE THREAD

**Issue by onshop** [dstreet/dependsOn#3]

**Comment by Decadence** [comment]
Why is this closed? I didn't find this option in docs.

**Comment by dstreet** [comment]
This was not closed by me. I guess @onshop no longer needed that feature? I will reopen.

**Comment by Decadence** [comment]
Thanks

**Comment by onshop** [comment]
Sorry, can't remember why I closed it. Maybe clicked the wrong button.
