### ISSUE TITLE
onEnable / onDisable don't work on document ready.

### ISSUE THREAD

**Issue by Decadence** [dstreet/dependsOn#38]
Hello.
If I set onEnable / onDisable options it doesn't work on initial page load, only after manual changes in dependency (check radio / checkbox).
What I want is they trigger depends on dependency initial state right after I call dependsOn on element.
State of the dependent element calculates fine but these callbacks don't fire.

Thanks for plugin.

**Comment by Decadence** [comment]
@dstreet Any ideas?)

**Comment by dstreet** [comment]
Fixed this.

**Comment by Decadence** [comment]
Thanks!
