### ISSUE TITLE
where is the min file

### ISSUE THREAD

**Issue by shorif2000** [dstreet/dependsOn#43]
i dont see this file anywhere  dependsOn.min.js when i use composer to download from bower/asset

**Comment by dstreet** [comment]
If you only want the min file and are not installing with npm, you can download the release: https://github.com/dstreet/dependsOn/releases/tag/v1.5.1

**Comment by shorif2000** [comment]
i use composer bower assets to manage all libraries, can the min file not be added to bower-assets?
